### ISSUE TITLE
Dynamic Excel Sheet

### ISSUE THREAD

**Issue by prajectory** [DPGAlliance/publicgoods-review-webapp#1]
@ricardomiron It says In-store in the status. Can you please let me know if it is done or not completed?
Make the excel sheet dynamic to reflect changes on the webapp. The excel sheet must have columns for user name, emails, latest communication, and DPG reviewer meeting updates and assignees as well.

**Comment by ricardomiron** [comment]
Not sure which Excel sheet this is referring to, but from the fields mentioned above (e.g. `DPG reviewer meeting updates`) does not sound like that is the data export feature for admins, where is the "In-store" status displayed? @PelinSmines

**Comment by PelinSmines** [comment]
This issue was under "Bugs and System Changes DPGA" project and its status was "In-store". I moved it under the DPGA Review Portal project where we keep simple Kanban staging; so it's having "To do" status now. I cannot see what in-store means in that board. It could mean "in progress". So Not sure if this was started to be developed. 
Could this excel sheet be about the recruitment of DPGs? Or  clarifications before these were part of the portal? If you cannot think of any excel sheet which is critical to have under this issue, we may just close it.

**Comment by ricardomiron** [comment]
@PelinSmines I see what you are referring to, it was basically a stage to put new features on a backlog for future development. But I still don´t know which Excel file this is referring to, might as well have been a manually updated tracker for engagement with applicants outside of the platform. That would not be too relevant anymore.
